### ISSUE TITLE
craft cli for auth scaffolding generates incorrect joi validation schema 

### ISSUE THREAD

**Issue by ashwin-sureshkumar** [supercharge/supercharge#30]
Steps reproduce: 

1. Scaffold new superchargejs 
2. run `node craft make:auth` 
3. Start server 

App crashes with error: `Error: Invalid schema content: (email.$_root.alternatives)` 

hapi 18 supports Joi 16, but the validation schema needs to be wrapped with `Joi.object()`. Below is the reference issue. 

https://github.com/hapijs/joi/issues/2107

**Comment by iamwebwiz** [comment]
Hi @ashwin-sureshkumar, do you have an idea if this has been fixed yet?

**Comment by iamwebwiz** [comment]
Hi @ashwin-sureshkumar, do you have an idea if this has been fixed just yet?
