### ISSUE TITLE
[ bug ] cannot navigate  to / or /hello

### ISSUE THREAD

**Issue by acidiney** [supercharge/supercharge#49]
Hey, @marcuspoehls 
Hope you doing fine.

I have generated a new app, using the command `npm init @supercharge/app@latest supercharge`, and there are the deps versions on `package.json`:

```json
"dependencies": {
    "@supercharge/console": "~3.4.0",
    "@supercharge/contracts": "~3.4.0",
    "@supercharge/core": "~3.4.0",
    "@supercharge/encryption": "~3.4.0",
    "@supercharge/facades": "~3.4.0",
    "@supercharge/http": "~3.4.0",
    "@supercharge/session": "~3.4.0",
    "@supercharge/strings": "~1.28.0",
    "@supercharge/view": "~3.4.0"
  },
  "devDependencies": {
    "@supercharge/eslint-config-typescript": "~2.3.0",
    "@supercharge/tsconfig": "~4.0.0",
    "@swc-node/register": "~1.5.1",
    "@types/node": "~18.6.3",
    "eslint": "~8.21.0",
    "nodemon": "~2.0.19",
    "typescript": "~4.7.4"
  }
```

- Macbook Pro 2019

## Problem
Running the command `npm run dev` and going browse to `/` or `/hello`, this error happen:
![image](https://github.com/supercharge/supercharge/assets/24493328/11f8e887-8e48-459f-be5e-a42e11612aa4)
![image](https://github.com/supercharge/supercharge/assets/24493328/bcd5e80d-8e7d-4403-adc7-090fc49f2323)

Could you help me please?

**Comment by acidiney** [comment]
![image](https://github.com/supercharge/supercharge/assets/24493328/53d1b9ab-c58c-4808-adbf-799ebb5c3f4c)

Solved by commenting this line

**Comment by marcuspoehls** [comment]
@acidiney Hey Acidiney, thanks for sharing this issue and your solution. Can you please look into this issue in more detail and send a pull request to fix it? Maybe it’s a dependency problem or incompatibility with a Node.js version.

**Comment by marcuspoehls** [comment]
@acidiney Hi Acidiney, I updated the dependencies of this project and refined the configuration files. Generating a new project works seamlessly now. You may give it another try 

```bash
npm init @supercharge/app@latest my-supercharge-project
```
